
// API 1
// get all the users details from the data base 
GET http://localhost:4000/
###
// API 2
// post the new user into data base. 
//user is auto incremented
// create a new user by chnaging the details below and run
POST http://localhost:4000/user/
Content-Type: application/json

{
  "username": "Rohit",
  "email": "rohit@gmail.com",
}






###
// update the user details based on user ID given 
//API 4
PUT http://localhost:4000/user/2/
Content-Type: application/json

{
  "username": "Sumit",
  "email": "sumit@gmail.com",
}

### 
// Delete the user details by the given user Id 
// API 5 
DELETE http://localhost:4000/user/1/




GET http://localhost:4000/comments/


POST http://localhost:4000/comment/
Content-Type: application/json

{
  "content": "Great job!",
  "author_id": 1,
  "blog_id":1,
}





PUT http://localhost:4000/comment/2/
Content-Type: application/json

{
  "content": "Great job!",
  "author_id": 2,
  "blog_id":2,
}


DELETE http://localhost:4000/comment/1/
