###
// get all the users details from the data base 
GET http://localhost:4000/


###
// create a new user by chnaging the details below and run
POST http://localhost:4000/user/
Content-Type: application/json

{
  "username": "Rohit",
  "email": "rohit@gmail.com",
}


###
// update the user details based on user ID given 
PUT http://localhost:4000/user/2/
Content-Type: application/json

{
  "username": "Sumit",
  "email": "sumit@gmail.com",
}

### 
// Delete the user details by the given user Id 
DELETE http://localhost:4000/user/1/


###
GET http://localhost:4000/comments/

###
POST http://localhost:4000/comment/

{
    content: "Done!",
}

###
PUT http://localhost:4000/comment/2/

{
    content: "Very Bad",
}


###
DELETE http://localhost:4000/comment/2/